name: Continuous Integration

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '18'

            - name: Install dependencies
              run: yarn install

            - name: Run Linter
              run: nx lint venci2

            - name: Check Formatting
              run: nx format:check

            - name: Run Tests
              run: nx test venci2
